### ISSUE TITLE
Transfer of responsibilities request

### ISSUE THREAD

**Issue by iArnold** [earl/vim-automkdir#1]
Dear Andreas,

Rumour has it, you have the access code to the Github repository rebol/rebol.
Rebol community is bound with hands tied behind the back without admins to take care of updating this repository.

If you indeed have the key to unlock the standoff
I kindly request you to hand over the key to a trusted source.

This 'trusted source' does not have to be me, though I am available and promiss to hand it in turn over in a responsible way.

Kind regards,

Arnold
Netherlands

**Comment by earl** [comment]
Dear Arnold! rebol/rebol is Carl's repository. I suggest you talk to Carl instead. All the best, Andreas

**Comment by iArnold** [comment]
Hi Andreas,

Thank you very much for your reply, even when you have a good reason to never want to have anything to do with Rebol again.

At least we can go back to Carl now.

Kind regards, all the best for you too,

Arnold

**Comment by earl** [comment]
I don't have any such reason. I do hold Rebol very dearly. In any case, if you want to chat, I'd prefer you simply send me an email instead of diverting Github's issue tracker from its intended use :)
